provenance-io/walletconnect-js

checkWebDemo.js, package-lock.json, package.json
=> run a check for webDemo before installing things for it. Version up

package.json
=> version up, tell npm to include checkwebdemo.js file

package.json
=> update to just have npm start run the npm install for webDemo

package.json, src/services/methods/connect.js
Instead of passing nested data on connect just pass the object with the values the apps will care about
closes: #XXXX
---
=> Non nesting data on connect

package.json, src/Components/QRCodeModal/QRCodeModal.js, webDemo/src/App.js
…se custom props on QRCodeModal.
Add customization into QRCodeModal.  Update webdemo to use custom props on QRCodeModal.
closes: #XXXX
---
=> QRCodeModal custom props

package.json, src/contexts/walletConnectContext.js
Quick fix for calling an old method that doesn't exist anymore on unmount
closes: #XXXX
---
=> version up.  Fix missed rename of removeAllListeners

package.json, src/services/walletConnectService.js
…e, which would read from storage values.  Instead use defaultState which just starts with empty values.  Version up
When using resetState use defaultState not initialState since that pulls from localStorage.
closes: #XXXX
---
=> resetState adjustment

package.json, src/contexts/walletConnectContext.js, src/services/walletConnectService.js
version up.  Fix network check since it wouldn't show up in the constructor when initialized
closes: #XXXX
---
=> Initial network value fix

package.json, src/services/methods/customAction.js
=> version up.  update to not hex encode

package-lock.json, package.json, src/consts/urls.js
- Version up
- Update Bridge URL to Figure
closes: #XXXX
---
=> New Bridge

package.json, src/services/methods/customAction.js, webDemo/src/consts/allActions.js
=> custom action

package.json, src/services/methods/customAction.js
=> update to no longer decode before hex

README.md, package.json, src/consts/urls.js
keep bridge as figure, have walletconnect commented out if we ever need it.  Version up.  Update readme for vanilla js setup
closes: #XXXX
---
=> Update readme for vanilla js

package.json, src/contexts/walletConnectContext.js, src/services/methods/connect.js, src/services/walletConnectService.js, webDemo/src/App.js, webDemo/src/Components/Dropdown/Dropdown.js, webDemo/src/consts/bridgeUrls.js, webDemo/src/consts/index.js
Allow padding a custom bridge value into the webdemo (from a list)
closes: #XXXX
---
=> Custom Bridge

package.json, src/services/methods/connect.js, webDemo/src/Components/AccountInfo/AccountInfo.js
version up.  Update peer with session updates.  Update setting JWT into state on connect
closes: #XXXX
---
=> Sign JWT with Connect

package.json, webDemo/src/Components/AccountInfo/AccountInfo.js
version up
fix name issue
remove disconnect from webdemo when not connected
closes: #XXXX
---
=> quick bug fix

package.json, src/Components/QRCodeModal/QRCodeModal.js, src/consts/urls.js
version up.  Update qrcodemodal to use firebase to get prov wallet url.  Add urls and apikey to consts
closes: #XXXX
---
=> QR Code Modal updates

package.json, src/Components/QRCodeModal/QRCodeModal.js
decode then recode the link value to normalize how it gets transferred
closes: #XXXX
---
=> Link decoding

package.json, src/services/walletConnectService.ts, src/types/BroadcastResults.ts, src/types/index.ts
Fix missing type on addListener
closes: #XXXX
---
=> Typescript fix

package.json, src/services/methods/customAction.ts, src/types/CustomActionData.ts, src/types/CustomActionResults.ts
Allow for multiple messages in an array when sending a customAction
closes: #XXXX
---
=> Custom Action Batch Requests

README.md, package.json, src/services/methods/index.ts, src/services/methods/sendCoin.ts, src/services/methods/sendHash.ts, src/services/walletConnectService.ts, src/types/SendCoinData.ts, src/types/index.ts, webDemo/src/consts/allActions.js
Add in new sendCoin Method.  Update readme.  Mark sendHash as deprecated
closes: #XXXX
---
=> sendCoin Method

package.json, src/services/methods/customAction.ts
add description to customAction return object
closes: #XXXX
---
=> Dev to main

package.json, src/types/CustomActionData.ts, src/types/SendCoinData.ts, src/types/SendHashData.ts, webDemo/src/App.js, webDemo/src/Components/Actions/Action.js, webDemo/src/consts/allActions.js
Update types for gasPrice.  Update webdemo to allow customizing gasPrice and defaulting to Figure gas prices
closes: #XXXX
---
=> Develop into main

.github/workflows/bump-tag-version.yml, README.md, package.json, src/consts/connectionTimeouts.ts, src/contexts/walletConnectContext.tsx, src/services/methods/connect.ts, src/services/methods/signJWT.ts, src/services/walletConnectService.ts, src/types/SignJWTData.ts, src/types/index.ts, webDemo/src/Components/CountdownTimer/CountdownTimer.js, webDemo/src/Components/Subheader/Subheader.js, webDemo/src/consts/allActions.js
- Version up
- Readme updates
- No longer using timeout based on mainnet/testnet
- Demo countdown timer will never go below 0
- signJWT method takes in an optional expiration value
- New github workflow to autotag
closes: #XXXX
---
=> Dev into Main

package.json, src/Components/QRCodeModal/QRCodeModal.tsx
Main production v1 release
closes: #XXXX
---
=> Version 1.0.0

package.json, src/Components/QRCodeModal/QRCodeModal.tsx
Encode the QR code url when copied or used in Urls
closes: #XXXX
---
=> QR Code URL encoding

package.json, src/Components/QRCodeModal/QRCodeModal.tsx
Add a new custom extension id input
closes: #XXXX
---
=> Custom Extension ID Input

package-lock.json, src/types/BaseResults.ts
=> add number as type option within BaseResults

package.json, src/Components/QRCodeModal/QRCodeModal.tsx
Add in missing extension change
closes: #XXXX
---
=> QR code setting proper event

package.json, src/services/methods/customAction.ts, src/services/methods/sendHash.ts, src/services/methods/signMessage.ts
customAction and sendHash now trigger chrome extension as needed
closes: #XXXX
---
=> Chrome Extension updates

package-lock.json, package.json
Add Babel Runtime Dependency
closes: #XXXX
---
=> Add Babel Runtime Dependency

.huskyrc, README.md, package-lock.json, package.json, src/Components/QRCodeModal/QRCodeModal.tsx, src/Components/QRCodeModal/index.ts, src/Components/index.ts, src/index.ts, src/service.ts
New non-react export location
closes: #XXXX
---
=> New non-react export location

babel.config.js, package-lock.json, package.json
Correctly apply babel/runtime to build, move back to dev deps
closes: #XXXX
---
=> Develop => Main

package-lock.json, package.json
Move babel runtime back to deps
closes: #XXXX
---
=> move babel runtime back to deps

package.json
Version up, include umd folder for npm.
closes: #XXXX
---
=> dev => main

package.json, src/Components/QRCodeModal/QRCodeModal.tsx, src/consts/index.ts, src/consts/urls.ts, src/consts/walletAppEvents.ts, src/consts/walletList.ts, src/images/index.ts, src/images/walletIcons.ts, src/services/methods/cancelRequest.ts, src/services/methods/connect.ts, src/services/methods/customAction.ts, src/services/methods/delegateHash.ts, src/services/methods/markerActivate.ts, src/services/methods/markerAdd.ts, src/services/methods/markerFinalize.ts, src/services/methods/sendCoin.ts, src/services/methods/sendHash.ts, src/services/methods/sendHashBatch.ts, src/services/methods/signJWT.ts, src/services/methods/signMessage.ts, src/services/walletConnectService.ts, src/types/BroadcastResults.ts, src/types/WalletList.ts, src/types/index.ts, webDemo/src/App.js
- Version up
- Significant updates to QRCodeModal (react.js)
- New consts file holding WALLET_LIST which is all the possible current wallets
- Update all methods to now pass a "date" in the metadata
- Update all methods to now call a wallet callback action based on the active wallet (from WALLET_LIST)
- Add Figure wallet to list of desktop wallets
- WalletList wallets may go into dev mode to not automatically be rendered in QRCodeModal (react)
- QRCodeModal can use a devWallets param to force show dev wallets
closes: #XXXX
---
=> WalletList and Surrounding Updates

package.json, src/Components/QRCodeModal/QRCodeModal.tsx, src/consts/walletList.ts, webDemo/src/App.js
- Version up
- Set prov ext wallet as dev
- Update demo to show prov ext dev wallet
- Show message when no wallets visible
closes: #XXXX
---
=> Move Prov-ext wallet to dev mode

package.json, src/types/CustomActionData.ts
- version up
- Update CustomActionData type
closes: #XXXX
---
=> Update CustomActionData type

package.json, src/services/methods/cancelRequest.ts, src/services/methods/customAction.ts, src/services/methods/delegateHash.ts, src/services/methods/markerActivate.ts, src/services/methods/markerAdd.ts, src/services/methods/markerFinalize.ts, src/services/methods/sendCoin.ts, src/services/methods/sendHash.ts, src/services/methods/sendHashBatch.ts, src/services/methods/signJWT.ts, src/services/methods/signMessage.ts, src/utils/index.ts, src/utils/rngNum.ts, webDemo/src/consts/allActions.js
Request ids are now correctly random numbers (previously always 1)
closes: #XXXX
---
=> Random Numbers

package.json, src/utils/rngNum.ts
Change default length of rng to 16 for js
closes: #XXXX
---
=> Dev to Main update

package.json, src/Components/QRCodeModal/QRCodeModal.tsx, src/consts/walletList.ts, src/types/WalletList.ts, src/umd.ts, webDemoVanilla/es5/index.html, webDemoVanilla/es5/main.js
- Update demos
- Export WALLET_LIST from umd.
- Update QrCodeModal copy for prov ext wallet.  Run wallet self check/redirect
- Update wallets to have optional self check and url values
- Version up
closes: #XXXX
---
=> Wallet Self-Existence Check

.eslintignore
allow global.d.ts to passthrough
closes: #XXXX
---
=> EslintIgnore update

.gitignore, src/types/global.d.ts
forgot to add to gitignore, only previously changes eslintignore
closes: #XXXX
---
=> Add changes to gitignore

package.json, src/consts/urls.ts
- Version up
- Update Figure Wallet URL
closes: #XXXX
---
=> Figure Wallet URL

README.md, package.json, src/Components/QRCodeModal/QRCodeModal.tsx
- Version up
- Update QRCodeModal to display a reload message when leaving the page to install an extension
- Update readme to note depreciated method sendHash
closes: #XXXX
---
=> QRCodeModal Reload Notification

.github/workflows/deploy.yml, package.json
- Version up
- Add missing build step into git actions deploy
closes: #XXXX
---
=> Add missing build step of github deploy

examples/example-react/package-lock.json, tsconfig.json, webpack.config.js
Quick fix to get build working, no version needed, never made it to npm
closes: #XXXX
---
=> Webpack quickfix

examples/example-react/src/Page/Connect.tsx, package.json, src/Components/QRCodeModal/QRCodeModal.tsx, src/consts/walletList.ts, src/types/WalletList.ts
Add option for figure mobile wallet when in mobile view (dev option)
closes: #XXXX
---
=> Figure Mobile Option

README.md, package.json, src/services/methods/sendMessage.ts, src/services/walletConnectService.ts, src/types/SendMessageData.ts
Add in feePayer optional param into sendMessage data
closes: #XXXX
---
=> Fee Payer to SendMessage

README.md, package.json, src/services/methods/signMessage.ts
Update to no longer hex the string messages as they come in
closes: #XXXX
---
=> signMessage Hex Update

README.md, package.json, src/services/methods/sendMessage.ts, src/services/walletConnectService.ts, src/types/SendMessageData.ts
Rename feePayer to feeGranter
closes: #XXXX
---
=> Rename feePayer to feeGranter

README.md, examples/example-react/package-lock.json, examples/example-react/src/Page/SendMessage.tsx, examples/example-react/src/theme/Theme.tsx, package-lock.json, package.json, src/consts/walletList.ts, src/types/WalletList.ts, src/types/global.d.ts
Update to add Figure Extension into core wallet list
closes: #XXXX
---
=> Figure Extension Wallet

package.json, src/services/methods/sendMessage.ts, src/services/walletConnectService.ts, src/types/SendMessageData.ts
v2.1.1
Add extra params to add into metadata for sendMessage: memo, timeoutHeight, extensionOptions, nonCriticalExtensionOptions, feePayer
closes: #XXXX
---
=> Update Send Message Data

README.md, examples/example-js-es6/package.json, examples/example-react/package-lock.json, examples/example-react/package.json, examples/example-react/src/Components/Checkbox/Checkbox.tsx, examples/example-react/src/Components/Checkbox/index.ts, examples/example-react/src/Components/index.ts, examples/example-react/src/Page/Connect.tsx, package.json, src/services/methods/connect.ts, src/services/walletConnectService.ts
v2.1.5
- Allow custom connection param for required address
- Allow custom connection param for opting out of groups
- Update demo app to show these options
closes: #XXXX
---
=> Connection Params

examples/example-js-es6/package.json, examples/example-react/package.json, package.json
v2.1.6
- Version up so new changes go out to npm from previous merge
closes: #XXXX
---
=> Version up

examples/example-js-es6/package.json, examples/example-react/package-lock.json, examples/example-react/package.json, examples/example-react/src/Page/SignMessage.tsx, package-lock.json, package.json, src/services/walletConnectService.ts
v2.1.7
- Most async methods now return results allowing dApps to await them instead of using WINDOW_MESSAGES
closes: #XXXX
---
=> Async Return Methods

README.md, examples/example-js-es6/package.json, examples/example-react-vite/package-lock.json, examples/example-react-vite/package.json, examples/example-react-vite/src/Page/Connect.tsx, examples/example-react/package.json, package.json, scripts/versionUp.js, src/services/methods/connect/connect.ts, src/services/methods/connect/createConnector.ts, src/services/methods/sendWalletAction.ts, src/services/walletConnectService.ts, src/types/ConnectData.ts, src/types/WalletConnectService.ts
- Update connect method to have new params for individualAddress and groupAddress
- Update readme to reflect the new connect params
- Update a few types around groupAccounts
- Update example vite dApp to use new connect params
closes: #XXXX
---
=> Walletconnect URI Connect Params

examples/example-js-es6/package.json, examples/example-react-vite/package-lock.json, examples/example-react-vite/package.json, examples/example-react-vite/src/Page/SendCoin.tsx, examples/example-react/package.json, package-lock.json, package.json
- v3.0.0-develop.16
- Add extra typings to package.json
- Update example app
closes: #XXXX
---
=> Typings and example app

README.md, examples/example-js-es6/package.json, examples/example-react-vite/package-lock.json, examples/example-react-vite/package.json, examples/example-react-vite/src/Page/Connect.tsx, examples/example-react/package.json, package.json, src/Components/QRCodeModal/QRCodeModal.tsx, src/consts/urls.ts, src/consts/walletAppIds.ts, src/consts/walletList/extension.ts, src/consts/walletList/hosted.ts, src/consts/walletList/index.ts, src/consts/walletList/mobile.ts, src/services/methods/connect/connect.ts, src/services/methods/connect/createConnector.ts, src/services/walletConnectService.ts, src/types/WalletConnectService.ts, src/types/WalletList.ts
- Renamed all figure_web to now be figure_hosted
- Remove connect param for noPopup
- Added connect method param for walletAppId
- New state value for dynamicUrl, lives w/in state.modal object (used for mobile wallet linking)
- Updated Figure Hosted wallet URL
- Figure Hosted wallet will now always open as a popup (no longer new page)
- Removed references to any Provenance Wallet
- Updated variable names for wallets in wallet_list
closes: #XXXX
---
=> Connect Method Updates

examples/example-react-vite/package-lock.json, examples/example-react-vite/package.json, examples/example-react-vite/src/Components/Results/Results.tsx, examples/example-react-vite/src/Page/Connect.tsx, package.json, src/Components/QRCodeModal/QRCodeModal.tsx, src/consts/urls.ts, src/index.ts, src/services/methods/connect/connect.ts, src/services/methods/connect/createConnector.ts, src/services/methods/sendMessage.ts, src/services/methods/sendWalletAction.ts, src/services/methods/signHexMessage.ts, src/services/methods/signJWT.ts, src/services/walletConnectService.ts, src/types/Broadcast.ts
Update the shape and names for broadcast result types
closes: #XXXX
---
=> Broadcast Types Update

LICENSE
Change spelling
closes: #XXXX
---
=> update license spelling

examples/example-js-es6/package.json, examples/example-react-vite/package-lock.json, examples/example-react-vite/package.json, examples/example-react/package.json, package-lock.json, package.json, src/consts/walletList/hosted.ts
- v3.0.1
- Update the wallet display names for Figure Hosted.  The new display name is "Figure Account".
closes: #XXXX
---
=> Update Wallet Display Names

examples/example-react-vite/package-lock.json, examples/example-react-vite/package.json, package-lock.json, package.json
- v3.0.8-develop.2
- Remove unused BIP32 Package
closes: #XXXX
---
=> Remove BIP32

examples/example-react-vite/package-lock.json, examples/example-react-vite/package.json, package.json, src/services/methods/connect/connect.ts
- v3.0.8-develop.5
- Add Figure Logo to center of QR Code
closes: #XXXX
---
=> QRCode will now have an image in the center

examples/example-react-vite/package-lock.json, examples/example-react-vite/package.json, package.json, src/services/methods/connect/connect.ts, src/services/methods/connect/createQRImage.ts
- v3.0.8-develop.6
- Update resolution for qrCodeImages
closes: #XXXX
---
=> QR Code Image Resolution

examples/example-react-vite/package.json, package.json, src/services/methods/sendMessage.ts
- v3.0.8-develop.7
- Add console logs before and after the await with sendMessage
closes: #XXXX
---
=> Add temp logs to sendMessage await

babel.config.js, examples/example-react-vite/package-lock.json, examples/example-react-vite/package.json, package-lock.json, package.json
- v3.0.9
- Add in @babel/plugin-transform-nullish-coalescing-operator
closes: #XXXX
---
=> Update Babel Config

README.md, examples/example-react-vite/package-lock.json, examples/example-react-vite/package.json, package.json, src/services/methods/connect/connect.ts, src/services/walletConnectService.ts, src/types/ConnectData.ts, src/types/WalletConnectService.ts, src/utils/getAccountInfo.ts
- Version up
- When connecting, expect to get back Figure Account Attributes in the account information. Store these attributes in the walletConnectService state
closes: #XXXX
---
=> Figure Account Attributes

src/services/walletConnectService.ts, src/types/WalletConnectService.ts, src/utils/getAccountInfo.ts
- Accidentally didn't fix one of the type names across the files.
closes: #XXXX
---
=> Quick Fix Rename

examples/example-react-vite/package-lock.json, examples/example-react-vite/package.json, examples/example-react-vite/src/Components/Card/Card.tsx, examples/example-react-vite/src/Page/Connect.tsx, examples/example-react-vite/src/consts/bridgeUrls.ts, examples/example-react-vite/src/theme/Theme.tsx, package.json, src/consts/provenance.ts, src/consts/walletList/extension.ts, src/types/WalletList.ts
- v3.3.0
- Add new field within WALLET_LIST items, walletUrls.  Only applies to extension currently.  Will hold and object of urls based on the browser allowing dApps to direct the user as needed.
- Demo app updated to allow for custom bridge (Figure demos already updated)
closes: #XXXX
---
=> WALLET_LIST walletUrls

examples/example-react-vite/package-lock.json, examples/example-react-vite/package.json, package-lock.json, package.json, src/consts/walletList/hosted.ts, src/hooks/useHostedWalletIframe.ts
Make the prod Figure Account wallet use an iframe instead of the popup so that it matches what is done in test currently.
=> Iframe for Hosted Wallet (Prod)

examples/example-react-vite/package-lock.json, examples/example-react-vite/package.json, examples/example-react-vite/src/Page/Connect.tsx, examples/example-react-vite/src/consts/bridgeUrls.ts, package-lock.json, package.json, src/consts/urls.ts, src/hooks/useHostedWalletIframe.ts, src/index.ts, src/services/methods/connect/connect.ts, src/services/methods/sendMessage.ts, src/services/methods/sendWalletAction.ts, src/services/methods/signHexMessage.ts, src/services/methods/signJWT.ts, src/services/walletConnectService.ts, src/types/WalletConnectService.ts, src/types/WalletList.ts
- v3.7.0
- Update Figure hosted wallet to use a max width of 100% when rendering the iframe
- Allow rendering iframe into a parent container (additional param on init method)
- Export additional types from index
- Update Figure test and prod bridge urls
- Update all wc customAction calls to not send through as silent.
---
=> feat(walletconnect-js) | Type Exports, CustomAction Notifications, and Hosted Iframe Updates

examples/example-react-vite/package-lock.json, examples/example-react-vite/package.json, package.json, src/Components/QRCodeModal/QRCodeModalNew.tsx, src/Components/QRCodeModal/stylesNew.css, src/services/walletConnectService.ts
- v3.7.2
- Split out work in progress QRCodeModal style changes, revert old QRCodeModal styles
- Change from develop version to patch version
closes: #XXXX
---
=> feat(walletconnect-js): Move develop version to patch, revert QRCodeModal style changes

examples/example-react-vite/package-lock.json, examples/example-react-vite/package.json, package-lock.json, package.json, src/consts/urls.ts, src/services/methods/connect/connect.ts
- Version up
- Shortlink QR code if possible, when not possible, default back to current QR code.  This should help slower/older devices scan.
closes: #XXXX
---
=> feat(WalletConnectJS) - Shortlink QR Code

README.md, examples/example-react-vite/package-lock.json, examples/example-react-vite/package.json, examples/example-react-vite/src/Page/Connect.tsx, package-lock.json, package.json, src/index.ts, src/services/methods/connect/connect.ts, src/services/methods/connect/createQRImage.ts, src/services/walletConnectService.ts, src/types/WalletConnectService.ts
- v3.10.0
- Ability to customize QR code image
- Default values will be same as current values in production
closes: #XXXX
---
=> feat(wcjs) - QR Code Options

examples/example-react-vite/package-lock.json, examples/example-react-vite/package.json, package-lock.json, package.json, src/services/methods/connect/connect.ts
- v3.10.1
- Was attempting to shorten the QR code for hosted/extension causing firebase 500s as those were not valid URLs.  Only shorten when mobile.
closes: #XXXX
---
=> bug(wcjs) - Fix shorten QR for non mobile wallets

examples/example-react-vite/package-lock.json, examples/example-react-vite/package.json, package-lock.json, package.json, src/services/methods/connect/connect.ts, src/services/walletConnectService.ts
- Used wrong is mobile var to only do it for test mobile wallet and still tried to generate link
closes: #XXXX
---
=> bug: Fix dynamic link in prod mobile wallet
